---

- name: Ensure ipset is installed (Debian).
  apt: pkg=ipset state=present
  when: ansible_os_family == 'Debian'


- name: Ensure ipset packages are installed (RedHat).
  yum:
    name: "ipset"
    state: present
    enablerepo: "{{ php_enablerepo }}"
  when: ansible_os_family == 'RedHat'


- name: Put up the block lists
  copy:
    src: "{{ item.src }}"
    dest: "/etc/firewall-{{ item.name }}.txt"
    owner: root
    group: root
    mode: 0644
  with_items: "{{firewall_blocklists}}"
  notify: restart firewall

- name: Copy firewall ipset script into place.
  template:
    src: 'firewall-upd8ipset.sh.j2'
    dest: "/etc/firewall-upd8ipset.sh"
    owner: root
    group: root
    mode: 0744
  when: firewall_mode == 'chain'
  notify: restart firewall